# Page admin routing
monsieurbiz_sylius_cms_page_admin:
    resource: |
        alias: monsieurbiz_cms_page.page
        section: admin
        permission: true
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show', 'update']
        redirect: update
        grid: monsieurbiz_cms_page
        vars:
            all:
                subheader: monsieurbiz_cms_page.ui.pages_subheader
            index:
                icon: 'file alternate'
    type: sylius.resource

# Ajax call to auto generate a slug for a page
monsieurbiz_sylius_cms_page_ajax_generate_page_slug:
    path: /page/generate-slug
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusCmsPagePlugin\Controller\Admin\Page\PageSlugController::generateAction

monsieurbiz_cms_page_admin_page_update:
    path: /pages/{id}/edit
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: monsieurbiz_cms_page.controller.page::updateAction
        _sylius:
            section: admin
            permission: true
            redirect: referer
            template: "@SyliusAdmin\\shared\\crud\\update.html.twig"
            vars:
                subheader: monsieurbiz_cms_page.ui.pages_subheader
                icon: file alternate

# Page preview
monsieurbiz_cms_page_admin_page_preview:
    path: /page/preview/{id}
    defaults:
        _controller: monsieurbiz_cms_page.controller.page::previewAction
        template: '@MonsieurBizSyliusCmsPagePlugin\\Admin\\Page\\preview.html.twig'
        _sylius:
            section: shop
