sylius_grid:
    templates:
        action:
            monsieurbiz_cms_page_preview: "@MonsieurBizSyliusCmsPagePlugin/Admin/Grid/Action/preview.html.twig"
    grids:
        monsieurbiz_cms_page:
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_cms_page.model.page.class%'
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            limits: [25, 50, 100, 200]
            sorting:
                id: desc
            fields:
                id:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.id
                    sortable: ~
                code:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.code
                    sortable: ~
                title:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.title
                    sortable: translation.title
                channels:
                    type: twig
                    label: sylius.ui.channels
                    options:
                        template: '@SyliusAdmin/shared/grid/field/channels.html.twig'
                enabled:
                    type: twig
                    label: monsieurbiz_cms_page.ui.form.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/grid/field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                        label: monsieurbiz_cms_page.ui.actions.create
                item:
                    update:
                        type: update
                    preview:
                        type: monsieurbiz_cms_page_preview
                    delete:
                        type: delete
            filters:
                code:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.code
                title:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.title
                    options:
                        fields: [translation.title]
                enabled:
                    type: boolean
                    label: monsieurbiz_cms_page.ui.form.enabled
                content:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.content
                    options:
                        fields: [translation.content]
                channel:
                    type: entity
                    label: sylius.ui.channel
                    options:
                        fields: [channels.id]
                    form_options:
                        class: "%sylius.model.channel.class%"
